version: '3.1'

services:
  db:
    image: mysql:8.4
    # platform: linux/amd64
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./binary/8.4:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Admin123@

  #adminer:
    #image: adminer:4.8.1
    #restart: always
    #ports:
      #- 8081:8081
